import type { NationalityOption } from "../../src/types.js";

// ISO 3166-1 alpha-2 officially assigned country and territory codes (249 entries).
// Names are generated by the platform ICU data so the enumeration stays complete
// without maintaining a second, error-prone translation table.
export const ISO_3166_ALPHA_2_CODES = `
AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ
BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ
CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ
DE DJ DK DM DO DZ
EC EE EG EH ER ES ET
FI FJ FK FM FO FR
GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY
HK HM HN HR HT HU
ID IE IL IM IN IO IQ IR IS IT
JE JM JO JP
KE KG KH KI KM KN KP KR KW KY KZ
LA LB LC LI LK LR LS LT LU LV LY
MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ
NA NC NE NF NG NI NL NO NP NR NU NZ
OM
PA PE PF PG PH PK PL PM PN PR PS PT PW PY
QA
RE RO RS RU RW
SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ
TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ
UA UG UM US UY UZ
VA VC VE VG VI VN VU
WF WS
YE YT
ZA ZM ZW
`.trim().split(/\s+/);

const displayNames = (locale: string) => new Intl.DisplayNames([locale], { type: "region" });

export function isoNationalityOptions(): NationalityOption[] {
  const zh = displayNames("zh-CN");
  const zhTw = displayNames("zh-TW");
  const en = displayNames("en");
  return ISO_3166_ALPHA_2_CODES.map(code => ({
    code,
    nameZh: zh.of(code) || code,
    nameZhTw: zhTw.of(code) || code,
    nameEn: en.of(code) || code,
    dialingCode: "",
    source: "iso-3166" as const,
  }));
}

export function mergeSupplierNationalities(
  supplierItems: Array<Omit<NationalityOption, "source">>,
): NationalityOption[] {
  const fallback = new Map(isoNationalityOptions().map(item => [item.code, item]));
  const merged = new Map<string, NationalityOption>();
  for (const supplier of supplierItems) {
    const code = supplier.code.trim().toUpperCase();
    if (!/^[A-Z]{2,3}$/.test(code)) continue;
    const iso = fallback.get(code);
    merged.set(code, {
      code,
      nameZh: supplier.nameZh || iso?.nameZh || code,
      nameZhTw: supplier.nameZhTw || iso?.nameZhTw || supplier.nameZh || code,
      nameEn: supplier.nameEn || iso?.nameEn || code,
      dialingCode: supplier.dialingCode || "",
      source: "flink",
    });
  }
  // If a supplier catalogue omits an officially assigned ISO entry, retain it as
  // standards-backed reference data so the form still offers the complete enum.
  for (const item of fallback.values()) {
    if (!merged.has(item.code)) merged.set(item.code, item);
  }
  return [...merged.values()].sort((left, right) => left.code.localeCompare(right.code));
}
